error: the main function has to be called main
 --> ui-tests/main-async.rs:7:4
  |
7 | fn fail() {}
  |    ^^^^
